name: Treble GSI Config Request
description: Request or document a Treble GSI build configuration.
title: "[Treble GSI Config] <short description>"
labels: ["gsi", "build-config"]
body:
  - type: input
    id: source_url
    attributes:
      label: Source URL
      description: The repo or manifest URL for the ROM source (e.g., https://github.com/LineageOS/android.git)
      placeholder: "https://github.com/LineageOS/android.git"
    validations:
      required: true
  - type: input
    id: branch
    attributes:
      label: Branch
      description: The branch or manifest branch to use (e.g., lineage-21.0, master, etc.)
      placeholder: "lineage-21.0"
    validations:
      required: true
  - type: input
    id: lunch_target
    attributes:
      label: Lunch Target
      description: The lunch target for the build (e.g., aosp_arm64_ab-userdebug)
      placeholder: "aosp_arm64_ab-userdebug"
    validations:
      required: true
  - type: input
    id: patches_source
    attributes:
      label: Patches Source (optional)
      description: Optional. A URL to a repo containing patches to apply, or leave blank if not needed.
      placeholder: "https://github.com/example/patches.git"
    validations:
      required: falsevvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
