name: New Treble ROM Request
description: Provide details for a new Treble ROM request.
title: "[New Treble ROM]: "
labels: ["enhancement", "treble"]
assignees: []

body:
  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      description: Specify the architecture.
      options:
        - ARM
        - ARM64
        - x86
        - x86_64

  - type: input
    id: rom_source
    attributes:
      label: ROM Source
      description: Provide the source URL or repository for the ROM.
      placeholder: e.g., https://github.com/example/rom

  - type: input
    id: patches_src
    attributes:
      label: Patches Source
      description: Provide the source URL or repository for the patches.
      placeholder: e.g., https://github.com/example/patches

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Any other relevant information. Note: DO NOT PUT ANYTHING IN HERE UNLESS IT IS DEVICE CRUCIAL INFORMATION. THE PROCESS WILL TAKE VERY LONG IF THIS FIELD IS NOT LEFT BLANK.
      placeholder: Provide any additional details here.
